### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by jamiemul** [smellyriver/tankinspector#5]
Crash log
`2017-06-01 16:16:51,633 [11] INFO PackageStream - open package file scripts/item_defs/vehicles/common/optional_devices.xml from C:\Games\World_of_Tanks\./res/packages/scripts.pkg
2017-06-01 16:16:51,651 [11] ERROR Program - an first chance exception occurred: 
System.Xml.XmlException: 'Element' is an invalid XmlNodeType.
   at System.Xml.XmlReader.ReadEndElement()
2017-06-01 16:16:51,746 [1] FATAL MainWindowViewModel - database load failed
System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: 'Element' is an invalid XmlNodeType.
   at System.Xml.XmlReader.ReadEndElement()
   at Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   at Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   at Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   at Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Xml.XmlException: 'Element' is an invalid XmlNodeType.
   at System.Xml.XmlReader.ReadEndElement()
   at Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   at Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   at Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   at Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

2017-06-01 16:16:51,748 [1] ERROR Program - an first chance exception occurred: 
System.InvalidOperationException: database load failed ---> System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: 'Element' is an invalid XmlNodeType.
   at System.Xml.XmlReader.ReadEndElement()
   at Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   at Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   at Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   at Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Smellyriver.TankInspector.MainWindowViewModel.OnDatabaseLoaded()
2017-06-01 16:16:51,837 [1] ERROR Program - an first chance exception occurred: 
System.InvalidOperationException: database load failed ---> System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: 'Element' is an invalid XmlNodeType.
   at System.Xml.XmlReader.ReadEndElement()
   at Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   at Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   at Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   at Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   at Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Smellyriver.TankInspector.MainWindowViewModel.OnDatabaseLoaded()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by hillin** [comment]
@jamiemul what version of WOT are you using?

**Comment by jamiemul** [comment]
@hillin 9.19 as far as I can tell.

**Comment by DrLivesey2** [comment]
RU region crash client
WoT v0.9.19.0,1
TI v1.8.1
Win 7 64 bit


log: [sti.txt](https://github.com/smellyriver/tankinspector/files/1049149/sti.txt)

**Comment by Nullmaruzero** [comment]
Same here.
WOT: EU 0.9.19 with the micropatch.
TI: 1.8.1
OS: Win 10 x64
```
2017-06-03 17:22:35,881 [12] ERROR Program - an first chance exception occurred: 
System.Xml.XmlException: Element 'Element' jest nieprawidlowym typem XmlNodeType.
   w System.Xml.XmlReader.ReadEndElement()
2017-06-03 17:22:37,180 [1] FATAL MainWindowViewModel - database load failed
System.AggregateException: Wystapil przynajmniej jeden blad. ---> System.Xml.XmlException: Element 'Element' jest nieprawidlowym typem XmlNodeType.
   w System.Xml.XmlReader.ReadEndElement()
   w Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   w Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   w Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   w Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
   --- Koniec sladu stosu wyjatków wewnetrznych ---
---> (Wyjatek wewnetrzny #0) System.Xml.XmlException: Element 'Element' jest nieprawidlowym typem XmlNodeType.
   w System.Xml.XmlReader.ReadEndElement()
   w Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   w Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   w Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   w Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()<---

2017-06-03 17:22:37,197 [1] ERROR Program - an first chance exception occurred: 
System.InvalidOperationException: database load failed ---> System.AggregateException: Wystapil przynajmniej jeden blad. ---> System.Xml.XmlException: Element 'Element' jest nieprawidlowym typem XmlNodeType.
   w System.Xml.XmlReader.ReadEndElement()
   w Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   w Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   w Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   w Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
   --- Koniec sladu stosu wyjatków wewnetrznych ---
   --- Koniec sladu stosu wyjatków wewnetrznych ---
   w Smellyriver.TankInspector.MainWindowViewModel.OnDatabaseLoaded()
2017-06-03 17:22:37,440 [1] ERROR Program - an first chance exception occurred: 
System.InvalidOperationException: database load failed ---> System.AggregateException: Wystapil przynajmniej jeden blad. ---> System.Xml.XmlException: Element 'Element' jest nieprawidlowym typem XmlNodeType.
   w System.Xml.XmlReader.ReadEndElement()
   w Smellyriver.TankInspector.Modeling.SectionDeserializableImpl.Deserialize(ISectionDeserializable this, XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Commodity.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.EquipmentDatabase.Deserialize(XmlReader reader)
   w Smellyriver.TankInspector.Modeling.Database.LoadCommonData()
   w Smellyriver.TankInspector.Modeling.Database.FullyLoad()
   w Smellyriver.TankInspector.Modeling.Database.Load(Boolean fullyLoad, Nullable`1 currentDatabaseKey)
   w Smellyriver.TankInspector.MainWindowViewModel.<>c.<BeginLoad>b__79_0()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
   --- Koniec sladu stosu wyjatków wewnetrznych ---
   --- Koniec sladu stosu wyjatków wewnetrznych ---
   w Smellyriver.TankInspector.MainWindowViewModel.OnDatabaseLoaded()
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Nullmaruzero** [comment]
My wild guess is, it could be caused by the new equipment/directives added in 9.19, which can be bought for Bonds from the new Ranked Battles mode.

I base my guess on the log. STI goes fubar just after it fetches optional_devices.xml
```
2017-06-04 14:17:53,155 [9] INFO PackageStream - open package file scripts/item_defs/vehicles/common/vehicle.xml from D:\Spil\World of Tanks\./res/packages/scripts.pkg
2017-06-04 14:17:53,170 [9] INFO PackageStream - open package file scripts/item_defs/vehicles/common/optional_devices.xml from D:\Spil\World of Tanks\./res/packages/scripts.pkg
2017-06-04 14:17:53,198 [9] ERROR Program - an first chance exception occurred: 
System.Xml.XmlException: Element 'Element' jest nieprawidlowym typem XmlNodeType.
   w System.Xml.XmlReader.ReadEndElement()
2017-06-04 14:17:53,836 [1] FATAL MainWindowViewModel - database load failed
```
Perhaps it has to do something with the fact that the new EQ disables the use of the regular counterpart.
(e.g Improved Rammer disables the possibility to mount a regular Rammer in the next slot).
Or directives, which have a seperate slot and are sometimes dependant on the modules installed (directive for rammer requires a rammer installed).

I cannot really see much in these .xmls because they seem to be half-encoded. Only some of the strings are readable, and I am not a WoT modder so I never tampered with the files so deep myself. Just tryin to help, because STI is a great tool and I see that you are a bit lonely here when it comes to contributors :(

**Comment by hillin** [comment]
I hope someone using the Russian game client could help to look into this problem. I guess it should be some straightforward XML parsing thing, but I'm currently not able to track all versions (in an internationalization term, cultures) of clients and guarantee all of them are working correctly.

**Comment by hillin** [comment]
@Nullmaruzero thank you for your enthusiasm :)
STI has a component named `XmlDecoder`, you can use the [`Decode`](https://github.com/smellyriver/tankinspector/blob/f390c8482a56c7d10abb0bcba36e99d4d8bb69ab/TankInspector/IO/XmlDecoding/XmlDecoder.cs#L55) method to get the source XML content. If you are familiar with C#, you can start from catching the exception that caused the crash, which will most likely reveal the malformatted XML section.

**Comment by Nullmaruzero** [comment]
Well, I do not really play with C#, I am on a level of a scriptkiddie but I play with PHP and JavaScript (NodeJS) + other Web-oriented stuff. As far as WoT clients are concerned, are they really that different? Using region changer for wot and/or selecting different language for the game in the launcher won't help in tracking the issue?
I will try to look into the source code and squeeze something out of it, but gotta prepare my system first.

And speaking of WoT version, I have EU version with English language. System though is Danish, but my Win10 user has language set to Polish, if it has anything to do with that. (The joys of international couples living together xD)

**Comment by hillin** [comment]
@Nullmaruzero actually it has nothing to do with client language, but client version. However in my region (China), updates tend to come several weeks later than other regions, so I may not be able to catch and fix those update-related issues in the first time.

**Comment by jamiemul** [comment]
I have a bit of experience with c# I will try to debug it when I get a chance.

**Comment by hillin** [comment]
Fixed https://github.com/smellyriver/tankinspector/commit/04181bc966dcbb11b8959a46908be23b50a5c13e

Grab a release here: https://github.com/smellyriver/tankinspector/releases/tag/1.9.0
